export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_FAILED = 'ADD_TO_CART_FAILED';

export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
export const SAVE_SHIPPING_ADDRESS_FAILED = 'SAVE_SHIPPING_ADDRESS_FAILED';

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export const SAVE_PAYMENT_METHOD_FAILED = 'SAVE_PAYMENT_METHOD_FAILED';